{{- if .Values.externalSecrets.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "deeptutor.fullname" . }}-pwd-gen
  labels:
    {{- include "deeptutor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "deeptutor.fullname" . }}
  labels:
    {{- include "deeptutor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "deeptutor.fullname" . }}
    template:
      data:
        OPENAI_API_BASE: {{ .Values.llm.apiBase | quote }}
        OPENAI_API_KEY: "{{ `{{ .apiKey }}` }}"
        DEFAULT_MODEL: {{ .Values.llm.model | quote }}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "deeptutor.fullname" . }}-pwd-gen
      rewrite:
        - transform:
            template: "apiKey"
---
{{- if .Values.sso.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "deeptutor.fullname" . }}-oauth2-proxy
  labels:
    {{- include "deeptutor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "deeptutor.fullname" . }}-oauth2-proxy
    template:
      data:
        OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
        OAUTH2_PROXY_CLIENT_SECRET: "acharya-keycloak-sso-secret-2026"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ `{{ .cookieSecret }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "deeptutor.fullname" . }}-pwd-gen
      rewrite:
        - transform:
            template: "cookieSecret"
{{- end }}
{{- end }}
