apiVersion: v1
kind: Service
metadata:
  name: {{ include "deeptutor.fullname" . }}
  labels:
    {{- include "deeptutor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
    {{- if .Values.sso.enabled }}
    - name: oauth2-proxy
      port: {{ .Values.sso.port | default 4180 }}
      targetPort: 4180
      protocol: TCP
    {{- end }}
  selector:
    {{- include "deeptutor.selectorLabels" . | nindent 4 }}
