{{- if and .Values.sso.enabled .Values.externalSecrets.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "lector.fullname" . }}-cookie-pwd
  labels:
    {{- include "lector.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lector.fullname" . }}-oauth2-proxy
  labels:
    {{- include "lector.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "lector.fullname" . }}-oauth2-proxy
    template:
      data:
        OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
        OAUTH2_PROXY_CLIENT_SECRET: "svadhyaya-keycloak-sso-secret-2026"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ `{{ .cookieSecret }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "lector.fullname" . }}-cookie-pwd
      rewrite:
        - transform:
            template: "cookieSecret"
{{- end }}
