{{- if and .Values.sso.enabled (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lector.fullname" . }}-oauth2-proxy
  labels:
    {{- include "lector.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.sso.keycloak.clientSecret | default "" | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.sso.cookie.secret | default "" | quote }}
{{- end }}

