{{- if and .Values.sso.enabled .Values.externalSecrets.enabled -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "calibre-web.fullname" . }}-cookie-secret
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  length: 32
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "calibre-web.fullname" . }}-oauth2-proxy
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore | default "aws-secretsmanager" }}
    kind: ClusterSecretStore
  target:
    name: {{ include "calibre-web.fullname" . }}-oauth2-proxy
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
        OAUTH2_PROXY_COOKIE_SECRET: "{{ `{{ .cookieSecret }}` }}"
        {{- if .Values.externalSecrets.remoteSecrets.clientSecretKey }}
        OAUTH2_PROXY_CLIENT_SECRET: "{{ `{{ .clientSecret }}` }}"
        {{- else }}
        OAUTH2_PROXY_CLIENT_SECRET: "{{ `{{ .generatedClientSecret }}` }}"
        {{- end }}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "calibre-web.fullname" . }}-cookie-secret
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cookieSecret"
    {{- if not .Values.externalSecrets.remoteSecrets.clientSecretKey }}
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "calibre-web.fullname" . }}-cookie-secret
      rewrite:
        - regexp:
            source: "(.*)"
            target: "generatedClientSecret"
    {{- end }}
{{- end }}
