{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "calibre-web.fullname" . }}-data
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.persistence.storageClass | default "gp3" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "15Gi" }}
{{- end }}
