apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-wearables.fullname" . }}-secret
  labels:
    {{- include "open-wearables.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- if .Values.sso.enabled }}
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.sso.keycloak.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.sso.cookie.secret | quote }}
  {{- end }}
