{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-wearables.fullname" . }}-secret
  labels:
    {{- include "open-wearables.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  SECRET_KEY: {{ .Values.secretKey | default "c0e482390f7a6348b301dc5341f486a9e1d82f7c653b8214b7e804f4a3952d71" | quote }}
  {{- if .Values.sso.enabled }}
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.sso.keycloak.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.sso.keycloak.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.sso.cookie.secret | quote }}
  {{- end }}
{{- end }}
