apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-wearables
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: open-wearables
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vgurukool/idp-aws.git
    targetRevision: main
    path: packages/open-wearables
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vgurukool
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
