apiVersion: v1
kind: Secret
metadata:
  name: {{ include "game.fullname" . }}
  labels:
    {{- include "game.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SECRET_KEY: {{ .Values.keycloak.jwtSecret | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.keycloak.clientId | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | quote }}
  KEYCLOAK_ISSUER: {{ .Values.keycloak.issuer | quote }}
