{{- if .Values.externalSecrets.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "freelingo.fullname" . }}-pwd-gen
  labels:
    {{- include "freelingo.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "freelingo.fullname" . }}
  labels:
    {{- include "freelingo.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "freelingo.fullname" . }}
    template:
      data:
        DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ `{{ .dbPassword }}` }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
        NEXTAUTH_SECRET: "{{ `{{ .nextauthSecret }}` }}"
        KEYCLOAK_ID: {{ .Values.keycloak.clientId | quote }}
        KEYCLOAK_SECRET: "{{ `{{ .clientSecret }}` }}"
        KEYCLOAK_ISSUER: {{ .Values.keycloak.issuer | quote }}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "freelingo.fullname" . }}-pwd-gen
      rewrite:
        - transform:
            template: "nextauthSecret"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "freelingo.fullname" . }}-pwd-gen
      rewrite:
        - transform:
            template: "clientSecret"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "freelingo.fullname" . }}-pwd-gen
      rewrite:
        - transform:
            template: "dbPassword"
{{- end }}
