apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freelingo.fullname" . }}
  labels:
    {{- include "freelingo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  NEXTAUTH_SECRET: {{ .Values.keycloak.nextauthSecret | quote }}
  KEYCLOAK_ID: {{ .Values.keycloak.clientId | quote }}
  KEYCLOAK_SECRET: {{ .Values.keycloak.clientSecret | quote }}
  KEYCLOAK_ISSUER: {{ .Values.keycloak.issuer | quote }}
