{{- if not .Values.auth.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.auth.postgresPassword | default "" | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.auth.databasePasswords.keycloak | default "" | quote }}
  LEARNHOUSE_DB_PASSWORD: {{ .Values.auth.databasePasswords.learnhouse | default "" | quote }}
  LITELLM_DB_PASSWORD: {{ .Values.auth.databasePasswords.litellm | default "" | quote }}
  BACKSTAGE_DB_PASSWORD: {{ .Values.auth.databasePasswords.backstage | default "" | quote }}
  FREELINGO_DB_PASSWORD: {{ .Values.auth.databasePasswords.freelingo | default "" | quote }}
  GAME_DB_PASSWORD: {{ .Values.auth.databasePasswords.game | default "" | quote }}
  ASHTA_DB_PASSWORD: {{ .Values.auth.databasePasswords.ashta | default "" | quote }}
  OPENFGA_DB_PASSWORD: {{ .Values.auth.databasePasswords.openfga | default "" | quote }}
  OPENWEARABLES_DB_PASSWORD: {{ .Values.auth.databasePasswords.openwearables | default "" | quote }}
  MAIC_DB_PASSWORD: {{ .Values.auth.databasePasswords.maic | default "" | quote }}
{{- end }}
