apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.auth.postgresPassword | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.auth.databasePasswords.keycloak | quote }}
  LEARNHOUSE_DB_PASSWORD: {{ .Values.auth.databasePasswords.learnhouse | quote }}
  LITELLM_DB_PASSWORD: {{ .Values.auth.databasePasswords.litellm | quote }}
  BACKSTAGE_DB_PASSWORD: {{ .Values.auth.databasePasswords.backstage | quote }}
  FREELINGO_DB_PASSWORD: {{ .Values.auth.databasePasswords.freelingo | quote }}
  GAME_DB_PASSWORD: {{ .Values.auth.databasePasswords.game | quote }}
  ASHTA_DB_PASSWORD: {{ .Values.auth.databasePasswords.ashta | quote }}
  OPENFGA_DB_PASSWORD: {{ .Values.auth.databasePasswords.openfga | quote }}
  OPENWEARABLES_DB_PASSWORD: {{ .Values.auth.databasePasswords.openwearables | quote }}
  MAIC_DB_PASSWORD: {{ .Values.auth.databasePasswords.maic | quote }}
